
<?php

  echo "
<nav id="navbar">
			<ul>
				<li><a class="active" href="index.php">Index</a></li>
				<li><a>Topic<span>&dtrif;</span></a>
				<ul>
					<li><a href="topic.php">Topic 1</a></li>
					<li><a href="topic2.php">Topic 2</a></li>
				</ul>
				</li>
				<li><a href="quiz.php">Quiz</a></li>
				<li><a href="enhancements.html">Enhancements</a></li>
				<li><a href="manage.php">Enhancements</a></li>
			</ul>
		</nav>";
?>
