<?php

  echo "
  <footer>
			<section class='footer-content'>
				<h3>B*TCH CROC</h3>
				<p>Group Project for COS10026</p>
				<section class='email'>
				<a href='mailto:103998991@student.swin.edu.au'>Ryan's Contact Email</a>
    			<a href='mailto:103989568@student.swin.edu.au'>Elishua's Contact Email</a>
   				<a href='mailto:103988837@student.swin.edu.au'>Alexander's Contact Email</a>
    			<a href='mailto:103797693@student.swin.edu.au'>Senil's Contact Email</a>
    			<a href='mailto:103983890@student.swin.edu.au'>Liam's Contact Email</a>
				</section>
			</section>
			<section class='footer-bottom'>
				<p>&#169; Swinburne University of Technology. Designed by <span> B*TCH CROC</span></p>
			</section>
		</footer> ";

?>
